<Project>
  <PropertyGroup>
	<KapuschFacebookFeatures Condition="'$(KapuschFacebookFeatures)' == ''">Login</KapuschFacebookFeatures>
    <UseKapuschFacebookInteropFromSource Condition="'$(UseKapuschFacebookInteropFromSource)' == ''"
      >false</UseKapuschFacebookInteropFromSource
    >
    <DisableKapuschFacebookInteropNativeAssets
      Condition="'$(DisableKapuschFacebookInteropNativeAssets)' == ''"
      >false</DisableKapuschFacebookInteropNativeAssets
    >
  </PropertyGroup>
</Project>
